### ISSUE TITLE
Update Front-End for Testnet Contracts

### ISSUE THREAD

**Issue by evgongora** [Vagabonds-Labs/cofiblocks#82] opened 2024-12-12 13:44 UTC
## Objective:

Ensure the front-end is configured to interact with the deployed testnet contracts.

## Steps:

Update contract addresses in the front-end to point to the deployed testnet versions.
Replace ABIs in the front-end with testnet-specific ABIs.
Ensure front-end interaction with the testnet contracts is functional.

Blocked by #81

**Comment by jaykayudo** [comment] 2024-12-12 14:09
Can i work on this?

I am a full stack developer with ample experience in building innovative and scalable solutions. on the blockchain side, i bring expertise in DAPP development, smart contract design and integration of several chains technology.

I will update the frontend as soon as the blocked issue is resolves and make a PR as soon as possible

**Comment by Kingsuite** [comment] 2024-12-12 14:12
May I be assigned to this?

**Comment by melnikga** [comment] 2024-12-12 14:35
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by josephchimebuka** [comment] 2024-12-12 14:52
Is it okay if I tackle this?

**Comment by gadyrcdz** [comment] 2024-12-12 15:07
Mind if I try this one? I want to learn more about these issues and this one gonna help me a lot. Also, I'm a member of the community Dojo Coding.

**Comment by ryzen-xp** [comment] 2024-12-12 15:12
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects etc .

I can update the front-end to interact with the deployed testnet contracts, including updating contract addresses, replacing ABIs, and ensuring smooth front-end interaction. Please assign this issue to me.

Thank you!

**Comment by Belloabraham121** [comment] 2024-12-12 15:12
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by fabrobles92** [comment] 2024-12-12 15:13
Fab here,
I have contributed to several web 3 projects including Dojo Engine, where I have deployed and interact with starknet contracts. I am familiar with Abi code and how to compile contract to obtain it. I think that can help me tackling this issue

**Comment by tasneemtoolba** [comment] 2024-12-12 15:19
I applied to #81 , so can I work on both tasks? I'm also a full-stack developer, so I will manage to handle it easily.

**Comment by BrunoAmbricca** [comment] 2024-12-12 15:24
I would like to work on this issue

**Comment by Jagadeeshftw** [comment] 2024-12-12 15:24
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by 1nonlypiece** [comment] 2024-12-12 15:25
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by ShantelPeters** [comment] 2024-12-12 15:28
I’d like to help with this.

**Comment by Luluameh** [comment] 2024-12-12 15:29
Is this issue still available?
I can work on it 
Estimated Completion Time: 1 day

**Comment by Supa-mega** [comment] 2024-12-12 15:49
I’d like to help with this.

**Comment by akintewe** [comment] 2024-12-12 15:51
Hi, I'm interested in taking on the this task. I am a frontend/ UIUX developer and i have experience in working with detailed designs. I've reviewed the requirements and I'm confident I can deliver. I'd love to discuss further and get started. Looking forward to hearing from you. ETA 8hours :)

**Comment by Amarjeet325** [comment] 2024-12-12 16:57
May I pick this up?

**Comment by Benjtalkshow** [comment] 2024-12-12 17:25
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment] 2024-12-12 17:31
Can I work on this, please?

**Comment by mimisavage** [comment] 2024-12-12 17:38
Can I contribute to this one?

**Comment by OWK50GA** [comment] 2024-12-12 18:36
Is it okay if I take this?
I can handle this

**Comment by od-hunter** [comment] 2024-12-12 19:02
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I have experience in html, css, JavaScript, TypeScript, cairo and rust.

To solve this issue, I'll take the following steps:
1. I'll import the marketplace contract ABI into the backend or frontend service responsible for handling NFT listings. I'll also use a blockchain interaction library (e.g., ethers.js, StarkNet.js) to call the create_product method.
2. I'll add input fields for price and stock in the NFT listing form. I'll also use form validation libraries (e.g., Formik, Yup) to ensure correct data formats for numeric fields like price and stock.
3. Next, I'll validate inputs locally in the frontend and on submission in the backend. I'll also create a backend API endpoint to process the form submission and interact with the marketplace contract.
4. I'll call the create_product method on the marketplace contract using the provided details and implement a loading spinner to indicate transaction progress. I'll also display a success message or error notification based on transaction results using state management (e.g., Redux, Context API).
5. Lastly, I'll write unit and integration tests to validate the listing process using mock contracts and test utilities.

I'll push a pr within 2 days upon assignment.
Kindly assign me please I'm up for the tax.

**Comment by TheSQLguy** [comment] 2024-12-12 20:01
So, for testing purposes, I will make sure that the front-end is interacting with the testnet contracts by updating contract addresses in the front-end code to refer to their respective testnet versions. At the same time, I will update the existing ABIs with the respective ABIs for the testnet versions of the contracts. Having updated the above, I will test the front-end and ensure it communicates properly with the deployed contracts as intended.

**Comment by Baronvil** [comment] 2024-12-12 20:29
Would love to tackle this!

**Comment by Yunusabdul38** [comment] 2024-12-12 20:51
May I take this issue on?

**Comment by emmz3230** [comment] 2024-12-12 21:48
Let me handle this issue!

I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

Having experience in hackathons, I know this will be a simple task for me to do.

**Comment by Superior212** [comment] 2024-12-12 22:01
Hey! I'm Superior,
I'm a member of BuidlGuidl and have contributed to various projects such as:
CoinSafe
Web3Bridge
GuildAudit
I haven’t contributed to any OnlyDust projects yet, but I’m eager to use my experience to make a strong impact on this task.
Plan to Solve the Issue:
Study the Codebase: I’ll review the existing structure and functionality to understand the current implementation.
Understand the Problem: I’ll carefully read the issue details to comprehend the task at hand fully.
Leverage Resources: I’ll utilize any provided resources or references within the issue to guide my solution.
Seek Clarifications: If I encounter challenges, I’ll ask questions in the Telegram group to ensure steady progress.
Submit PR: Once the solution is implemented, I’ll open a pull request and await your feedback.
I’m excited to contribute and am confident in my ability to solve this issue effectively!

**Comment by wheval** [comment] 2024-12-12 22:28
Hello, I'm Wheval an experienced Frontend and Blockchain Developer.

Can i work on this?

I have worked on something similar for Peerprotocol.
I would update the contract addresses.
I would replace the ABIs to use the testnet ABIs of the updated Contract addresses. The ABIs can be gotten from the blockchain explorer.
I would also ensure the frontend interacts with the contract properly.

ETA is 2 days.

**Comment by caxtonacollins** [comment] 2024-12-12 23:22
Can I jump on this task?

**Comment by DuendexCR** [comment] 2024-12-13 00:24
Can I be assigned to this?

**Comment by Psalmuel01** [comment] 2024-12-13 06:45
## I am super experienced in writing staking contracts logic.

**About me**:
I am a software engineer with strong technical skills and expertise in developing fully functional dapps. I also have experience in writing Cairo smart contracts, so I know the modalities around it. I have developed many such frontends with excellent integrations as you'd find all around my repos.

More recently, I have contributed to some starkness projects like Custos Diretriz (https://github.com/Psalmuel01/Custos-Dapp) and Chainevents (https://github.com/Psalmuel01/chainevents-contracts). My GitHub has a lot of proof of work, as well.

Leveraging on my skills and experience, l am confident in my ability to tackle new challenges and also solve complex technical issues.

Tackling this issue
• Given my experience in integrating frontend with smartcontracts, I will ensure the frontend is exactly configured to fit the deployed contract, until it functions seamlessly.

ETA: 12 hours

**Comment by Emmanex01** [comment] 2024-12-13 07:44
Could I grab this task?
I'm Emmanuel Tochukwu, 
A Frontend developer, proficient in Reactjs, tailwindcss, typescript, Cairo Programming Languages.

**Comment by Dorcas18** [comment] 2024-12-13 12:17
Can I take care of this issue?

**Comment by ekumamatthew** [comment] 2024-12-13 12:29
Is it okay if I take this?

**Comment by 3th-Enjay** [comment] 2024-12-13 12:31
Could I take over this issue?

**Comment by Jemiiah** [comment] 2024-12-21 00:19
@evgongora can I work on this issue

**Comment by bitfalt** [comment] 2024-12-21 07:30
hey @fabrobles92, just letting you know I've created the PR solving the issue that was blocking yours. You can check the addresses of the smart contracts in the PR description.
This is the PR #95.

**Closed** 2024-12-24 16:48 UTC
Labels: good first issue, ODHack11, rewarded
